print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>Hello Word - First Python Script run through Apache</title>")
print("</head>")
print("<body>")
print("<h2>Hello Word! This is my first Python Script run through Apache</h2>")
print("</body>")
print("</html>")
